/* Relatorio geral de todos os clientes */

SELECT NOME, SEXO, EMAIL, CPF, RUA, BAIRRO, CIDADE, ESTADO, TIPO, NUMERO 
FROM CLIENTE
INNER JOIN ENDERECO ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

/* relatorio de homens */

SELECT NOME, SEXO, EMAIL, CPF, RUA, BAIRRO, CIDADE, ESTADO, TIPO, NUMERO 
FROM CLIENTE
INNER JOIN ENDERECO ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
WHERE SEXO = 'M';

/*Corrigindo pessoas com sexo errado id: (11, 12, 13, 17, 18)*/
UPDATE CLIENTE 
SET SEXO = 'F'
WHERE IDCLIENTE IN (11, 12, 13, 17, 18);


/* quantidade de homens e mulheres */

SELECT SEXO, COUNT(1)
FROM CLIENTE
GROUP BY SEXO;

/* ids e email das mulheres que moram no centro do rio de janeiro e não tenham celulares */

SELECT IDCLIENTE, EMAIL
FROM CLIENTE
INNER JOIN ENDERECO ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
WHERE SEXO = 'F' AND CIDADE = 'RIO DE JANEIRO' AND BAIRRO = 'CENTRO' AND TIPO = 'RES';
