-- database: :memory:
/* Relatorio geral de todos os clientes */

SELECT NOME, SEXO, EMAIL, CPF, RUA, BAIRRO, CIDADE, ESTADO, TIPO, NUMERO 
FROM CLIENTE
INNER JOIN ENDERECO ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

/* relatorio de homens */

SELECT NOME, SEXO, EMAIL, CPF, RUA, BAIRRO, CIDADE, ESTADO, TIPO, NUMERO 
FROM CLIENTE
INNER JOIN ENDERECO ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
WHERE SEXO = 'M';

/*Corrigindo pessoas com sexo errado id: (11, 12, 13, 17, 18)*/
UPDATE CLIENTE 
SET SEXO = 'F'
WHERE IDCLIENTE IN (11, 12, 13, 17, 18);


/* quantidade de homens e mulheres */

SELECT SEXO, COUNT(1)
FROM CLIENTE
GROUP BY SEXO;

/* ids e email das mulheres que moram no centro do rio de janeiro e não tenham celulares */

SELECT C.IDCLIENTE, C.EMAIL, C.NOME, C.SEXO, T.TIPO, E.BAIRRO, E.CIDADE
FROM CLIENTE C
INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F' AND BAIRRO = 'CENTRO' AND CIDADE = 'RIO DE JANEIRO' AND (TIPO = 'RES' OR TIPO = 'COM'); 

/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR -- PROJEÇÃO
FROM CLIENTE C -- ORIGEM
INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE  --JUNÇÃO 
INNER JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE --JUNÇÃO 
WHERE TIPO = 'CEL' AND ESTADO = 'RJ';  -- SELEÇÃO


/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
 DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR 
FROM CLIENTE C 
INNER JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
WHERE SEXO = 'F' AND ESTADO = 'SP';


/*nome, email, nuemro, estado*/
SELECT C.NOME,
       ifnull(C.EMAIL, '*****NÃO TEM EMAIL*****') AS EMAIL, 
       T.NUMERO,
       E.ESTADO
FROM CLIENTE C 
INNER JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE;

+---------+--------------------------+-----------+--------+
| NOME    | EMAIL                    | NUMERO    | ESTADO |
+---------+--------------------------+-----------+--------+
| JOAO    | JOAO@GMAIL.COM           | 981142054 | PE     |
| JOAO    | JOAO@GMAIL.COM           | 431541545 | PE     |
| JOAO    | JOAO@GMAIL.COM           | 764365366 | PE     |
| JOAO    | JOAO@GMAIL.COM           | 091090908 | PE     |
| Maria   | MARIA@GMAIL.COM          | 981144243 | PE     |
| JOSE    | JOSE@GMAIL.COM           | 5623523I5 | PE     |
| JOSE    | JOSE@GMAIL.COM           | 768494030 | PE     |
| GABRIEL | GABRIEL@GMAIL.COM        | 981425676 | PE     |
| GABRIEL | GABRIEL@GMAIL.COM        | 542565262 | PE     |
| MARCAI  | MARCIA@GMAIL.COM         | 981415443 | PE     |
| ANDRE   | ANDRE@GLOBO.COM          | 68976565  | MG     |
| ANDRE   | ANDRE@GLOBO.COM          | 99656675  | MG     |
| KARLA   | KARLA@GMAIL.COM          | 33567765  | RJ     |
| KARLA   | KARLA@GMAIL.COM          | 88668786  | RJ     |
| KARLA   | KARLA@GMAIL.COM          | 55689654  | RJ     |
| DANIELE | DANIELE@GMAIL.COM        | 88687979  | RJ     |
| LORENA  | *****NÃO TEM EMAIL*****  | 88965676  | ES     |
| ANTONIO | ANTONIO@IG.COM           | 89966809  | PR     |
| ANTONIO | ANTONIO@UOL.COM          | 88679978  | SP     |
| ELAINE  | ELAINE@GLOBO.COM         | 99655768  | PR     |
| CARMEM  | CARMEM@IG.COM            | 89955665  | SP     |
| ADRIANA | ADRIANA@GMAIL.COM        | 77455786  | RJ     |
| ADRIANA | ADRIANA@GMAIL.COM        | 89766554  | RJ     |
| JOICE   | JOICE@GMAIL.COM          | 77755785  | RJ     |
| JOICE   | JOICE@GMAIL.COM          | 44522578  | RJ     |
+---------+--------------------------+-----------+--------+



